# data loading config
data_type: "fft"
problem_type: "regression"
window_size: 65536
test_sep_strategy: "record"
test_ratio: 0.2
flat_features: False
random_seed: 42

# nn model config
nn_model_dir: C:/Users/moam/OneDrive - Danmarks Tekniske Universitet/.D/University/PhD/Projects/Benchmarking/saved_models/TensorFlow/CNN/2024-03-06_18-01-02
nn_model_path: ${nn_model_dir}/tf/model/keras_format/model.keras
figures_save_dir: ${nn_model_dir}/figures

# svm model config
n_fft_partitions: 50
time_tag: null
experiment_save_dir: results/svm/${time_tag}
