# data loading config
data_type: "fft"
window_size: 65536
test_sep_strategy: "record"
test_ratio: 0.2
random_seed: 42

time_tag: null    # placeholder (will be filled by the script)

n_fft_partitions: 50
save_dir: results/svm/${time_tag}
